st = 'Hello World!' 
print(st[1:5])  #'ello' 
print(st[7:10]) #'orl'
print(st[3:20]) #'lo World!'
print(st[:5])   #'Hello' 
print(st[6:])   #'World!'
print(st[:-4])  #'Hello Wo'
print(st[-5:])  #'orld!'
print(st[-9:-3])#'lo Wor'
print(st[3:20:2]) #'l ol!'